### ISSUE TITLE
Bug: landingPage variable not linking to the correct metrics page

### ISSUE THREAD

**Issue by daviddetorres** [iamseth/oracledb_exporter#131]
The variable `landingPage` seems not to be taking ok the value of `metricPath` (appears empty).
https://github.com/iamseth/oracledb_exporter/blob/6f6b77414635b0e9ef99fe94c9c2f5cf711186b9/main.go#L33

It should work if the variable is declared after parsing the flags here: https://github.com/iamseth/oracledb_exporter/blob/6f6b77414635b0e9ef99fe94c9c2f5cf711186b9/main.go#L403

**Comment by Yannig** [comment]
I cannot reproduce your issue. If I run the docker image locally, the version is set with the good value.

Are you trying to run the exporter locally on your machine?

**Comment by daviddetorres** [comment]
I'm deploying the exporter in Kubernetes with this configuration: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracledb-exporter
  namespace: database-namespace
spec:
  selector:
    matchLabels:
      app: oracledb-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: oracledb-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9161"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: oracledb-exporter
        ports:
        - containerPort: 9161
        image: iamseth/oracledb_exporter
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: oracledb-exporter-secret
              key: datasource
        - name: CUSTOM_METRICS
          value: /tmp/custom-metrics.toml
        volumeMounts:
          - name:  custom-metrics
            mountPath:  /tmp/custom-metrics.toml
            subPath: custom-metrics.toml
      volumes:
        - name: custom-metrics
          configMap:
            defaultMode: 420
            name: custom-metrics               
```
The result is that the link `Metrics` goes to `/` instead of linking to `/metrics`.
