### ISSUE TITLE
prometheus-Common label application Questions

### ISSUE THREAD

**Issue by B-OPS-HUB** [iamseth/oracledb_exporter#213]
## Q 1

![image](https://user-images.githubusercontent.com/92511837/137278880-97bd8104-ba6c-4794-9750-87317bad16ca.png)  

- For example, as shown above, it is possible to distinguish the fields that are received by each sql statement in the field of prometheus.labels.instance, but where is the field generated?

### Current Query

```toml
[[metric]]
context = "sessions"
labels = [ "status", "type", "oracle_server_name" ]
metricsdesc = { value= "Gauge metric with count of sessions by status and type." }
request = "SELECT status, type, COUNT(*) as value, 'master1_oracleExporter' as oracle_server_name FROM v$session GROUP BY status, type"

[[metric]]
context = "resource"
labels = [ "resource_name", "oracle_server_name" ]
metricsdesc = { current_utilization= "Generic counter metric from v$resource_limit view in Oracle (current value).", limit_value="Generic counter metric from v$resource_limit view in Oracle (UNLIMITED: -1)." }
request="SELECT resource_name,current_utilization,CASE WHEN TRIM(limit_value) LIKE 'UNLIMITED' THEN '-1' ELSE TRIM(limit_value) END as limit_value FROM v$resource_limit"
```

![image](https://user-images.githubusercontent.com/92511837/137279367-cd328700-695e-4910-bb03-800301494812.png)
### Apply representative query

```toml
[[metric]]
context = "sessions"
labels = [ "status", "type", "oracle_server_name" ]
metricsdesc = { value= "Gauge metric with count of sessions by status and type." }
request = "SELECT status, type, COUNT(*) as value, 'master1_oracleExporter' as oracle_server_name FROM v$session GROUP BY status, type"

[[metric]]
context = "resource"
labels = [ "resource_name", "oracle_server_name" ]
metricsdesc = { current_utilization= "Generic counter metric from v$resource_limit view in Oracle (current value).", limit_value="Generic counter metric from v$resource_limit view in Oracle (UNLIMITED: -1)." }
request="SELECT resource_name,current_utilization,CASE WHEN TRIM(limit_value) LIKE 'UNLIMITED' THEN '-1' ELSE TRIM(limit_value) END as limit_value, 'master1_oracleExporter' as oracle_server_name FROM v$resource_limit"
```

![image](https://user-images.githubusercontent.com/92511837/137279237-dd7752df-603f-4a2a-80dd-0153dbd191e8.png)
  
- I added oracle_server_name for each of those queries, but I want to know how to apply a representative field that can distinguish each exporter when using two exporters once without such a method.
- Isn't there a good way to do it all at once in the preferences?
- I want to know how to create a field that applies to all queries and distinguishes each oracle db_exporter without adding columns to the query.

@Yannig @iamseth
