### ISSUE TITLE
oracledb_exporter has connection issue unable to pull custom metrics in Prometheus 

### ISSUE THREAD

**Issue by kram1947** [iamseth/oracledb_exporter#224]
time="2021-12-27T11:35:58Z" level=info msg="Starting oracledb_exporter master" source="main.go:543"
time="2021-12-27T11:35:58Z" level=info msg="Successfully loaded default metrics from: default-metrics.toml" source="main.go:518"
time="2021-12-27T11:35:58Z" level=info msg="Successfully loaded custom metrics from: /custom-metrics.toml" source="main.go:528"
time="2021-12-27T11:35:58Z" level=error msg="Error pinging oracle: driver: bad connection" source="main.go:215"
time="2021-12-27T11:35:58Z" level=info msg="Listening on :9161" source="main.go:579"
time="2021-12-27T11:36:10Z" level=error msg="Error pinging oracle: driver: bad connection" source="main.go:215"
time="2021-12-27T11:36:25Z" level=error msg="Error pinging oracle: driver: bad connection" source="main.go:215"
time="2021-12-27T14:21:10Z" level=error msg="Error pinging oracle: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor\n" source="main.go:215"

**Comment by gonzalez** [comment]
Can you share your DATA_SOURCE_NAME variable value ? Is this a RAC deployment ?

**Comment by pvk1103** [comment]
I am facing similar ORA-12514 issue.  How did this issue get resolved?

**Comment by ss185427** [comment]
If using Docker Compose (example for Oracle XE) -
```yaml
# Prometheus - Oracle DB exporter
  oracledbexp:
    image: iamseth/oracledb_exporter
    environment:
      - DATA_SOURCE_NAME=sys/123456@//oraclexedb:1521/XEPDB1?as=sysdba
    ports:
      - "9161:9161/tcp"
    depends_on:
      oraclexedb:
        condition: service_healthy
```
