### ISSUE TITLE
How to get Prometheus hexadecimal label value instead of decimal value?

### ISSUE THREAD

**Issue by timeforplanb123** [iamseth/oracledb_exporter#244]
custom-metrics.toml
----
```toml
[[metric]]
context = "user_data"
labels = [ "mac_addr" ]
metricsdesc = { status_flag = "status_flag." }
request = "SELECT mac_addr,status_flag FROM user_data"
```
oracle SQL Developer query result
----
```sql
select * from user_data
```
```text
+----------------+----------------+
| MAC_ADDR       | STATUS_FLAG    |
+----------------+----------------+
| 7085C2A7A6B2   | 1              |
+----------------+----------------+
```
`mac_addr` is a raw
`status_flag` is a number

sudo systemctl status oracledb_exporter
----
`sudo systemctl status oracledb_exporter` starts well:

```text 
Jul 28 14:38:28 prometheus systemd[1]: Starting Service for oracle telemetry client...
```

Current Prometheus metrics and question
----
```text
# my_prometheus:9161/metrics
# HELP oracledb_user_data_status_flag status_flag.
# TYPE oracledb_user_data_status_flag gauge
oracledb_user_data_status_flag{mac_addr="[112 133 194 167 166 178]"} 1
```

Why is `mac_addr` label in decimal format here and how to get / convert it to original hexadecimal? (7085C2A7A6B2 hex = 112 133 194 167 166 178 dec). In advance, thanks a lot for the answer.
