### ISSUE TITLE
Container fails to start on RHEL7

### ISSUE THREAD

**Issue by laurent-indermuehle** [iamseth/oracledb_exporter#304]
## I'm submitting a ...

- [X] bug report
- [ ] feature request

## What is the current behavior?

Everytime I start the image ghcr.io/iamseth/oracledb_exporter on RHEL7, it exits immediately.

`podman logs oracledb_exporter` output:
```
runtime/cgo: 
SIGABRT: abort
PC=0x7f46d9a8d26b m=0 sigcode=18446744073709551610

goroutine 
runtime: g 0: unknown pc 0x7f46d9a8d26b
stack: frame={sp:0x7ffef84ecad0, fp:0x0} stack=[0x7ffef7aedf50,0x7ffef84ecf60)
0x00007ffef84ec9d0:  0x0000000000e4164a 
0x00007ffef84ec9e0:  0x00000000009c2152  0x0000000000000004 
0x00007ffef84ec9f0:  0x0000000000e4164c  0x0000000000000000 
0x00007ffef84eca00:  0x00000000009c2cb1  0x0000000000000005 
0x00007ffef84eca10:  0x0000000000000000  
0x00007ffef84eca20:  0x0000000000000000
0x00007ffef84eca30: 
0x00007ffef84eca40:  0x0000000000000000  
0x00007ffef84eca50:  0x0000000000000000
0x00007ffef84eca60: 
0x00007ffef84eca70:  0x0000000000e4164b  
0x00007ffef84eca80:  0x0000000000000002
0x00007ffef84eca90
0x00007ffef84ecaa0
0x00007ffef84ecab0: 
0x00007ffef84ecac0:  0x0000000000000000  
0x00007ffef84ecad0: <0x0000000000000000
0x00007ffef84ecae0:  0x0000000000000006  0x00007f46de008a40 
0x00007ffef84ecaf0:  0x00000000019552e0  
0x00007ffef84ecb00:  0x0000000000e10ee0
0x00007ffef84ecb10:  0x00007f46d9bf2e70  0x00007f46d9a1d7fc 
0x00007ffef84ecb20:  0x0000000000000020 
0x00007ffef84ecb30:  
0x00007ffef84ecb40
0x00007ffef84ecb50:  0x0000000000000000  
0x00007ffef84ecb60:  0x0000000000000000
0x00007ffef84ecb70: 
0x00007ffef84ecb80:  0x0000000000000000  
0x00007ffef84ecb90:  0x0000000000000000
0x00007ffef84ecba0: 
0x00007ffef84ecbb0:  0x0000000000000000  0x9602dc8ca2bb8f00 
0x00007ffef84ecbc0:  0x00007f46d9bf2840  0x00007f46d9bf2840 
runtime: g 0: unknown pc 0x7f46d9a8d26b
stack: frame={sp:0x7ffef84ecad0, fp:0x0} stack=[0x7ffef7aedf50,
0x00007ffef84ec9d0:  0x0000000000e4164a 
0x00007ffef84ec9e0: 
0x00007ffef84ec9f0:  0x0000000000e4164c  0x0000000000000000
0x00007ffef84eca00:  0x00000000009c2cb1
0x00007ffef84eca10: 
0x00007ffef84eca20:  0x0000000000000000  
0x00007ffef84eca30:  0x0000000000000000
0x00007ffef84eca40:  0x0000000000000000  0x0000000000000000 
0x00007ffef84eca50:  0x0000000000000000  
0x00007ffef84eca60:  0x00000000009c3bb3
0x00007ffef84eca70:  0x0000000000e4164b  0x0000000000000000 
0x00007ffef84eca80:  0x0000000000000002  
0x00007ffef84eca90:  
0x00007ffef84ecaa0
0x00007ffef84ecab0
0x00007ffef84ecac0
0x00007ffef84ecad0: <0x0000000000000000  0x9602dc8ca2bb8f00 
0x00007ffef84ecae0:  0x0000000000000006 
0x00007ffef84ecaf0:  
0x00007ffef84ecb00:  0x0000000000e10ee0  0x00007f46d9a36c46 
0x00007ffef84ecb10:  0x00007f46d9bf2e70 
0x00007ffef84ecb20:  
0x00007ffef84ecb30:  0x0000000000000000  0x0000000000000000
0x00007ffef84ecb40:  0x0000000000000000 
0x00007ffef84ecb50:  
0x00007ffef84ecb60:  0x0000000000000000  0x0000000000000000
0x00007ffef84ecb70:  0x0000000000000000
0x00007ffef84ecb80:  0x0000000000000000 
0x00007ffef84ecb90:  0x0000000000000000 
0x00007ffef84ecba0:  0x0000000000000000  0x0000000000000000
0x00007ffef84ecbb0:  0x0000000000000000  0x9602dc8ca2bb8f00
0x00007ffef84ecbc0:  0x00007f46d9bf2840  0x00007f46d9bf2840

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc000044780 sp=0xc000044778 pc=0x46a560
runtime.main()
	/usr/local/go/src/runtime/proc.go:170 +0x6d fp=0xc0000447e0 sp=0xc000044780 pc=0x43ea0d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000447e8 sp=0xc0000447e0

rax    0x0
rbx    
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x6
rsp    0x7ffef84ecad0
r8     0x0
r9     
r10    0x8
r11    0x246
r12    0x16
r13    0x178
r14    0xe10ee0
r15    0x7f46b19ef35b
rip    0x7f46d9a8d26b
rflags 0x246
cs     
fs     0x0
gs     0x0

```

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

```
/usr/bin/podman container run -it --detach --name oracledb_exporter ghcr.io/iamseth/oracledb_exporter:0.4.4
```
I tried as root or in a special user.
I tried multiple releases: 0.4.4, 0.4.2, ....
On Fedora 37 it works fine.

## Please tell us about your environment:

podman system info: 

```
host:
  BuildahVersion: 1.11.7
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.el7_8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 372b4a12f1c2df4f70c280d41173b60acd3f1260'
  Distribution:
    distribution: '"rhel"'
    version: "7.8"
  MemFree: 601104384
  MemTotal: 16637550592
  OCIRuntime:
    name: runc
    package: runc-1.0.0-69.rc10.el7_9.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 17177767936
  SwapTotal: 17177767936
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: orasrv04
  kernel: 3.10.0-1127.18.2.el7.x86_64
  os: linux
  rootless: false
  uptime: 22896h 7m 19.54s (Approximately 954.00 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
