### ISSUE TITLE
Metric Scrape error

### ISSUE THREAD

**Issue by Bayardalai** [iamseth/oracledb_exporter#33]
Hi,

I'm using custom metric to collect some space usage. But this metric is not scraping
Here is my query "select round((space_used-space_reclaimable)*100/space_limit,1) fra_usage from  v$recovery_file_dest";

When i tested i cannot add metric request using this views v$recovery_file_dest, v$recovery_area_usage.
Other system views like v$sysmetric work fine.

What am i doing wrong?

Thanks,

**Comment by Yannig** [comment]
Can you provide the metric you try to define?

**Comment by Bayardalai** [comment]
Here is my TOML file content.

```
[[metric]]
context = "fra"
metricsdesc = {fra_usage = "Fast Recovery Area Usage %."}
request = "select round((space_used-space_reclaimable)*100/space_limit,1) fra_usage from  v$recovery_file_dest"

[[metric]]
context = "sysmetric"
labels = ["metric_name", "metric_unit"]
metricsdesc = { value= "Generic counter metric from v$sysmetric view in Oracle." }
request = "select metric_name,value,metric_unit from v$sysmetric where group_id=2"

[[metric]]
context = 'aas'
labels = ["wait_class"]
metricsdesc = {aas = "Average Active Sessions"}
request = '''
SELECT n.wait_class, ROUND (m.time_waited / m.INTSIZE_CSEC, 3) aas
  FROM v$waitclassmetric m, v$system_wait_class n
 WHERE m.wait_class_id = n.wait_class_id AND n.wait_class != 'Idle'
UNION
SELECT 'CPU', ROUND (VALUE / 100, 3) aas
  FROM v$sysmetric
 WHERE metric_name = 'CPU Usage Per Sec' AND GROUP_ID = 2
UNION
SELECT 'CPU_OS',
       ROUND ((prcnt.busy * parameter.cpu_count) / 100, 3) - aas.cpu
  FROM (SELECT VALUE     busy
          FROM v$sysmetric
         WHERE metric_name = 'Host CPU Utilization (%)' AND GROUP_ID = 2)
       prcnt,
       (SELECT VALUE     cpu_count
          FROM v$parameter
         WHERE name = 'cpu_count') parameter,
       (SELECT 'CPU', ROUND (VALUE / 100, 3) cpu
          FROM v$sysmetric
         WHERE metric_name = 'CPU Usage Per Sec' AND GROUP_ID = 2) aas
'''
```

**Comment by Yannig** [comment]
I don't get it: the request you provide return no row. Are you sure that your request is valid?

```sql
select
  round((space_used-space_reclaimable)*100/space_limit,1) fra_usage
from v$recovery_file_dest;
```
```no rows selected```

**Comment by Yannig** [comment]
If will you scrape your metrics, there's no result, the exporter will report a warning. But if it's fine (sometime, metrics are not present like asm disk group for example), you can add `ignorezeroresult = true` in the metric definition.

**Comment by Bayardalai** [comment]
No rows returning means that Fast Recovery Area isn't configured in you database.
In my case it's returning the result. Unfortunately getting error from exporter.

**Comment by Yannig** [comment]
In this case, add ignorezeroresult = true in your definition:

```toml
[[metric]]
context = "fra"
metricsdesc = {fra_usage = "Fast Recovery Area Usage %."}
request = '''
select
  round((space_used-space_reclaimable)*100/space_limit,1) fra_usage
from  v$recovery_file_dest
'''
ignorezeroresult = true
```

**Comment by Bayardalai** [comment]
In my case this query returns 1 row data.
But when i set `ignorezeroresult = true`  it ignores the error and no result for this query.

and another thing if i add this metric, exporter cannot start.
```
[[metric]]
context = "instance"
metricsdesc = { value = "Database Instance Name from v$parameter." }
request = "select value from v$parameter"
ignorezeroresult = true
```


if add some filtering to the query which returns 3 rows like below, exporter displays no result
```
[[metric]]
context = "instance1"
metricsdesc = { value = "Database Instance Name from v$parameter." }
request = '''
select name,value from v$parameter where name in ('instance_name','db_name','spfile')
'''
ignorezeroresult = true
```

**Comment by Yannig** [comment]
You are trying to export string value and Prometheus can only store numeric values. If you wan't to export informations about your database (version, name etc.), you can get them using fake value. Something like this may do the trick:

```toml
[[metric]]
context = "instance"
labels = ["name", "value"]
metricsdesc = { parameter = "Database Instance Name from v$parameter." }
request = "select name,value,1 as parameter from v$parameter where name in ('instance_name','db_name','spfile')"
```

With my test case, I get the following output:

```
# HELP oracledb_instance_parameter Database Instance Name from v$parameter.
# TYPE oracledb_instance_parameter gauge
oracledb_instance_parameter{name="db_name",value="ORCLCDB"} 1
oracledb_instance_parameter{name="instance_name",value="ORCLCDB"} 1
oracledb_instance_parameter{name="spfile",value="/opt/oracle/product/18c/dbhome_1/dbs/spfileORCLCDB.ora"} 1
```

**Comment by Yannig** [comment]
For the fra problem, can you provide the raw output you get?

**Comment by Bayardalai** [comment]
custom-metric
```
[[metric]]
context = "fra"
metricsdesc = {space_limit = "max size.", space_used = "used space.", space_reclaimable = "reclaimable space."}
request = "select space_limit,space_used,space_reclaimable from v$recovery_file_dest"

[[metric]]
context = "recovery_area"
metricsdesc = {fra_usage = "Fast Recovery Area Usage %."}
request = "select round((space_used-space_reclaimable)*100/space_limit,1) fra_usage from  v$recovery_file_dest"
```
sqlplus result:
```
SQL> select round((space_used-space_reclaimable)*100/space_limit,1) fra_usage from  v$recovery_file_dest;

 FRA_USAGE
----------
       2.8

SQL> select space_limit,space_used,space_reclaimable from v$recovery_file_dest;

     SPACE_LIMIT     SPACE_USED SPACE_RECLAIMABLE
---------------- -------------- -----------------
     12884901888    10248251392        9840569344
```
metrics result
```

oracledb_exporter_scrape_errors_total{collector="fra"} 3
oracledb_exporter_scrape_errors_total{collector="recovery_area"} 3
```

if i set `ignorezeroresult = true`, above errors ignored.

**Comment by Yannig** [comment]
Can you provide the log output from the exporter?

Before launching exporter, can you try to set NLS_LANG to AMERICAN_AMERICA.WE8ISO8859P1 this way:

```bash
export NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
```

**Comment by Bayardalai** [comment]
Yes, I tried to set NLS_LANG to AMERICAN_AMERICA.WE8ISO8859P1. No difference.
```
ERRO[1380] Error scraping for recovery_area : No metrics found while parsing  source=main.go:176
ERRO[1395] Error scraping for backup : No metrics found while parsing  source=main.go:176
ERRO[1395] Error scraping for fra : No metrics found while parsing  source=main.go:176
ERRO[1395] Error scraping for recovery_area : No metrics found while parsing  source=main.go:176
ERRO[1410] Error scraping for backup : No metrics found while parsing  source=main.go:176
ERRO[1410] Error scraping for fra : No metrics found while parsing  source=main.go:176
ERRO[1410] Error scraping for recovery_area : No metrics found while parsing  source=main.go:176
```

**Comment by Yannig** [comment]
Can you try this toml file:

```toml
[[metric]]
context = "fra"
metricsdesc = {space_limit = "max size.", space_used = "used space.", space_reclaimable = "reclaimable space."}
# request = "select space_limit,space_used,space_reclaimable from v$recovery_file_dest"
request = "select 12884901888 as space_limit,10248251392 as space_used,9840569344 as space_reclaimable from DUAL"

[[metric]]
context = "recovery_area"
metricsdesc = {fra_usage = "Fast Recovery Area Usage %."}
# request = "select round((space_used-space_reclaimable)*100/space_limit,1) fra_usage from  v$recovery_file_dest"
request = "select 2.8 as fra_usage from DUAL"
```

**Comment by Bayardalai** [comment]
Here is result
```
# HELP oracledb_recovery_area_fra_usage Fast Recovery Area Usage %.
# TYPE oracledb_recovery_area_fra_usage gauge
oracledb_recovery_area_fra_usage 2.8

# HELP oracledb_fra_space_limit max size.
# TYPE oracledb_fra_space_limit gauge
oracledb_fra_space_limit 1.2884901888e+10
# HELP oracledb_fra_space_reclaimable reclaimable space.
# TYPE oracledb_fra_space_reclaimable gauge
oracledb_fra_space_reclaimable 9.840569344e+09
# HELP oracledb_fra_space_used used space.
# TYPE oracledb_fra_space_used gauge
oracledb_fra_space_used 1.0248251392e+10
```

And another test result is here.
When i use ` v$recovery_file_dest or v$recovery_area_usage` views that has more than 1 row instead of `dual`, it's not working.


```
[[metric]]
context = "fra"
metricsdesc = {space_limit = "max size.", space_used = "used space.", space_reclaimable = "reclaimable space."}
request = "select 1 space_limit,1 space_used,1 space_reclaimable from v$recovery_file_dest"

[[metric]]
context = "recovery_area"
labels = ["usage"]
metricsdesc = {fra_usage = "Fast Recovery Area Usage %."}
request = "select  1 usage, 1 fra_usage from v$recovery_area_usage"

oracledb_exporter_scrape_errors_total{collector="fra"} 4
oracledb_exporter_scrape_errors_total{collector="recovery_area"} 4



SQL> select * from v$recovery_area_usage;

FILE_TYPE               PERCENT_SPACE_USED PERCENT_SPACE_RECLAIMABLE NUMBER_OF_FILES     CON_ID
----------------------- ------------------ ------------------------- --------------- ----------
CONTROL FILE                             0                         0               0          0
REDO LOG                                 0                         0               0          0
ARCHIVED LOG                         76.84                     76.84             255          0
BACKUP PIECE                             0                         0               0          0
IMAGE COPY                               0                         0               0          0
FLASHBACK LOG                         2.85                       .41               7          0
FOREIGN ARCHIVED LOG                     0                         0               0          0
AUXILIARY DATAFILE COPY                  0                         0               0          0

8 rows selected.

SQL> select * from v$recovery_file_dest;

 SPACE_LIMIT     SPACE_USED SPACE_RECLAIMABLE NUMBER_OF_FILES     CON_ID
---------------- -------------- ----------------- --------------- ----------
 12884901888    10267385344        9952812544             262          0
```

**Comment by Yannig** [comment]
Beware, if you retrieve multiple time the same metrics, you **must** have different label for each row.

Here is the correct declaration for recovery_area:

```toml
[[metric]]
context = "recovery_area"
labels = ["type"]
metricsdesc = {fra_usage = "Fast Recovery Area Usage %.", usage = "Usage in recovery area"}
request = "select  file_type as type, 1 usage, 1 fra_usage from v$recovery_area_usage"
```

Can you also give me the version you're using of Oracle?
