### ISSUE TITLE
Multi target broken after release 0.5.0

### ISSUE THREAD

**Issue by xafer337** [iamseth/oracledb_exporter#339]
Hi!

I was unsuccessfully trying to use /scrape endpoint in the last release of the exporter (0.5.1). 

Since version 0.5.0 it is not possible to send a http request to the endpoint `/scrape?target=foo:1521` where target is set to the DSN of the Oracle instance to scrape metrics from.

Looking at the code I saw that changes made on #308 removed that feature (done in #234) even though the README says the feature is still there.

Is there any chance that this feature will be included again?

**Comment by Yannig** [comment]
Hi @xafer337 

We have done some change in the 0.5 and I think we have broke this feature. Can you give me an example of Prometheus configuration + exporter configuration that was working in 0.4 and not in 0.5 anymore ?

Then I will fix this capacity.

**Comment by lscool66** [comment]
```yaml
  - job_name: "oracledb"
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9161
    static_configs:
      - targets:
          - oracle://10.142.1.22:1521
```
