### ISSUE TITLE
Log level environment variable Docker

### ISSUE THREAD

**Issue by OskarsPakers** [iamseth/oracledb_exporter#342]
## It does not seem to be possible to set log level when using Docker image.

- [x] feature request

## What is the expected behavior?

To be able to set log level through enviornment variables e.g.

```
  oracledb-exporter:
    image: ghcr.io/iamseth/oracledb_exporter:0.5.1
    ports:
      - 9161:9161
    environment:
      - DATA_SOURCE_NAME=oracle://system:MyPassword123@oracledb:1521/XE
      - NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
      - CUSTOM_METRICS=/custom-metrics.toml
      - ORACLE_VERSION=21
      - LOG_LEVEL=debug
```        

## What is the motivation / use case for changing the behavior?

When there is an issue with custom query e.g. "unsupported value type" I would like to get additional information of what went wrong.

## Please tell us about your environment:

Version: 0.5.1

**Comment by OskarsPakers** [comment]
There is a workaround though to add command parameter
```
  oracledb-exporter:
    image: ghcr.io/iamseth/oracledb_exporter:0.5.1
    command: --log.level=debug
    ports:
      - 9161:9161
    environment:
      - DATA_SOURCE_NAME=oracle://system:MyPassword123@oracledb:1521/XE
      - NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
      - CUSTOM_METRICS=/custom-metrics.toml
      - ORACLE_VERSION=21
      - LOG_LEVEL=debug
```
