### ISSUE TITLE
How to use Multi-Target Support?

### ISSUE THREAD

**Issue by dmitriy-shleht** [iamseth/oracledb_exporter#445]
I have Oracle RAC, I would like to collect metrics from two instances (nodes, ora01 and ora02)

## What is the current behavior?
I tried to specify them through a comma, but it does not work and I get a mistake
`oracle://SVC_ORACLEDB_EXPORTER:12345@ora01.fgr.my:1521/odaodb,ora02.fgr.my:1521/odaodb`

How do I need to set the connection string to two instances in the DSN ?

## What is the expected behavior?
I thought to turn to the copies I needed as it is written in readme
 `/scrape?target=ora01:1521` OR `scrape?target=ora02:1521`

## Please tell us about your environment:
Kubernetes

Version: 0.6.0

**Comment by valrusu** [comment]
Hi, I used 2 targets under a single job in Prometheus, and started 2 scrapers, each pointing to one specific instance:

```
  - job_name: oracle_job_name
    scrape_interval: 60s
    static_configs:
    - targets: ['localhost:9161','localhost:9162']
```

DSN used: oracle://dbuser:password@server:1521/service?sid=sidname
Used the scan name for server.

Hope this helps.
