### ISSUE TITLE
Could oracledb_exporter support multiple oracle instances ? 

### ISSUE THREAD

**Issue by xuanyuanaosheng** [iamseth/oracledb_exporter#64]
Could oracledb_exporter support multiple oracle instances ?  Like  read  oracle tnsnames.ora file.

**Comment by Yannig** [comment]
No, you need to launch multiple instances of the exporter and there's no plan to change this behaviour.

In Prometheus, it is not recommended to pool this type of component. Indeed, in case of failure of an instance, we will not know where the problem comes from.

In order to launch multiple exporters on the same machine, you can use Docker.

**Comment by mzs114** [comment]
@Yannig,

Assuming that by changing Port numbers I run multiple oracledb exporters on the same host without docker, but then how can I differentiate which metrics belong to which process(or oracle instance)?  
I mean is there a way to add custom tags?

I am using metricbeat and it allows one to add custom fields/env tags, by which one can group the collected data.

**Comment by Yannig** [comment]
You can add labels when you declare the base in Prometheus:

```
---
    targets:
      - host1:9991
    labels:
      oracle-sid: "MYSID1"
---
    targets:
      - host1:9992
    labels:
      oracle-sid: "MYSID2"
```
