### ISSUE TITLE
Prometheus Configuration Sample

### ISSUE THREAD

**Issue by juanrosero** [iamseth/oracledb_exporter#95]
Hello everyone,

This is a great project and I appreciate your efforts.

I'm looking for documentation to configure Prometheus and I cannot find it in the README.md file nor other places here. Can someone provide a sample on how to configure Prometheus please?

Keep up the good work!

Thanks,

**Comment by Yannig** [comment]
There's nothing special to do. You add the endpoint in Prometheus and you're done.

Here is a very basic example that should work:

```yaml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'oracle'
    static_configs:
      - targets: ['my-oracle-exporter-address:9161']
```
